### ISSUE TITLE
Notifications failing

### ISSUE THREAD

**Issue by SteveDemy** [vaadin/eclipse-plugin-legacy#743] opened 2017-05-19 19:47 UTC
Eclipse Neon.3 Release (4.6.3) raises an error message periodically and every time the Vaadin Notifications subwindow is opened.

An internal error occurred during: "Fetch all notifications".
org.json.simple.JSONObject cannot be cast to org.json.simple.JSONArray

**Comment by tsuoanttila** [comment] 2017-05-23 10:40
Duplicate of #708

**Closed as completed by tsuoanttila** 2017-05-23 10:40 UTC
Labels: duplicate
