### ISSUE TITLE
Eclipse plugin does not fail gracefully if version list cannot be downloaded

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#613] opened 2016-02-18 16:01 UTC
**Reported by John Ahlroos on 9 Dec 2014 09:16 UTC**
When the plugin fails to download the version list then you cannot create a  Vaadin project.

Stacktrace:

```
java.io.FileNotFoundException: /home2/workspaces3/wysiwyg-prototype/.metadata/.plugins/org.eclipse.pde.core/pde-junit/com.vaadin.integration.eclipse/VERSIONS_7 (No such file or directory)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
    at java.io.FileWriter.<init>(FileWriter.java:90)
    at com.vaadin.integration.eclipse.util.network.MavenVersionManager.downloadAvailableVersionsList(MavenVersionManager.java:92)
```

The plugin should be shipped with a version list as fallback if no network is available.

Migrated-From: http://dev.vaadin.com//ticket/15347

**Comment by makoivis** [comment] 2016-02-18 16:01
**Modified by John Ahlroos on 18 Dec 2015 08:00 UTC**

**Comment by hesara** [comment] 2016-03-08 16:45
Duplicate of #560

**Closed as completed by hesara** 2016-03-08 16:45 UTC
