### ISSUE TITLE
Better icon for compiling widget set

### ISSUE THREAD

**Issue by makoivis** [vaadin/eclipse-plugin-legacy#44] opened 2016-02-16 13:15 UTC
**Reported by Marko Gronroos on 10 Nov 2009 15:15 UTC**
I suppose the button with the Vaadin logo is not the final?

I need a more final button for taking a screenshot.

**Comment by makoivis** [comment] 2016-02-16 13:15
**Modified by Jouni Koivuviita on 11 Nov 2009 13:28 UTC**

**Comment by makoivis** [comment] 2016-02-16 13:15
**Modified by Artur Signell on 20 Nov 2009 13:11 UTC**

**Comment by makoivis** [comment] 2016-02-16 13:15
**Modified by Artur Signell on 23 Nov 2009 08:38 UTC**

**Comment by hesara** [comment] 2016-03-07 12:43
Duplicate of #185 (already closed)

**Closed as completed by hesara** 2016-03-07 12:43 UTC
